JustInTimeCompany/Controllers/FlightsController.cs
using Castle.DynamicProxy.Generators.Emitters.SimpleAST;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using JustInTimeCompany.Models;
using JustInTimeCompany.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Text.Json;

namespace JustInTimeCompany.Controllers
{
    public class FlightsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public FlightsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Flights
        public async Task<IActionResult> Index(string placeMode = "", Guid? placeId = null, string dateMode = "",
            DateTime? selectedDate = null)
        {
            ViewBag.PlaceMode = new List<string>() { "Any place", "From", "To" };
            ViewBag.DateMode = new List<string>() { "Both", "Departure", "Arrival" };
            var airports = await _context.Airports.ToListAsync();
            var flights = _context.Flights.ToList();
            flights.Sort((f1, f2) => f1.ScheduledDeparture.CompareTo(f2.ScheduledDeparture));
            var homeViewModel = new FlightListViewModel();
            homeViewModel.Airports = airports;
            homeViewModel.Flights = flights;
            if (!string.IsNullOrWhiteSpace(placeMode) && placeId is not null)
            {
                homeViewModel.Flights = placeMode switch
                {
                    "From" => flights.Where(f => f.From?.Id == placeId).ToList(),
                    "To" => flights.Where(f => f.To?.Id == placeId).ToList(),
                    _ => homeViewModel.Flights
                };
            }

            if (!string.IsNullOrWhiteSpace(dateMode) && selectedDate.HasValue)
            {
                homeViewModel.Flights = dateMode switch
                {
                    "Departure" => homeViewModel.Flights
                        .Where(f => f.ScheduledDeparture.Date == selectedDate.Value.Date)
                        .ToList(),
                    "Arrival" => homeViewModel.Flights
                        .Where(f => f.ScheduledArrival.Value.Date == selectedDate.Value.Date)
                        .ToList(),
                    _ => homeViewModel.Flights
                        .Where(f => f.ScheduledDeparture.Date == selectedDate.Value.Date ||
                                    f.ScheduledArrival.Value.Date == selectedDate.Value.Date)
                        .ToList(),
                };
            }


            return View(homeViewModel);
        }

        // GET: Flights/Details/5
        public async Task<IActionResult> Details(Guid? flightId)
        {
            if (flightId == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .FirstOrDefaultAsync(m => m.Id == flightId);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // GET: Flights/Create
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create()
        {
            var createFlightViewModel = new FlightViewModel();
            var airports = await _context.Airports.ToListAsync();
            var helicopters = await _context.Helicopters.ToListAsync();
            var pilots = await _userManager.GetUsersInRoleAsync("Pilot");
            createFlightViewModel.Airports = airports;
            createFlightViewModel.Helicopters = helicopters;
            createFlightViewModel.Pilots = pilots;
            return View(createFlightViewModel);
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FlightViewModel flightViewModel)
        {
            var flight = flightViewModel.Flight;
            if (flight == null) return NotFound();
            flight.From = await _context.Airports.SingleOrDefaultAsync(a => a.Id == flight.From.Id);
            flight.To = await _context.Airports.SingleOrDefaultAsync(a => a.Id == flight.To.Id);
            flight.Helicopter =
                await _context.Helicopters.SingleOrDefaultAsync(h => h.Id == flight.Helicopter.Id);
            flight.Pilot = _userManager.FindByIdAsync(flight.Pilot?.Id).Result;
            if (flight.From is null || flight.To is null || flight.Pilot is null || flight.Helicopter is null)
                return NotFound("Couldn't find required airport or pilot or helicopter.");
            var airports = await _context.Airports.ToListAsync();
            var helicopters = await _context.Helicopters.ToListAsync();
            var pilots = await _userManager.GetUsersInRoleAsync("Pilot");
            flightViewModel.Airports = airports;
            flightViewModel.Helicopters = helicopters;
            flightViewModel.Pilots = pilots;
            flightViewModel.Flights = await _context.Flights.ToListAsync();
            ModelState.Clear();
            if (TryValidateModel(flight))
            {
                if (flightViewModel.PilotCanFly())
                {
                    flight.Id = Guid.NewGuid();
                    _context.Add(flight);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                    ModelState.AddModelError("Flight.Pilot", "Sorry, requested pilot is not free at that date.");
            }

            return View(flightViewModel);
        }

        // GET
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> CreateMany()
        {
            ViewBag.Helicopters = await _context.Helicopters.ToListAsync();
            ViewBag.Pilots = await _userManager.GetUsersInRoleAsync("Pilot");
            ViewBag.Airports = await _context.Airports.ToListAsync();
            return View(new ManyFlightsViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateMany(ManyFlightsViewModel viewModel)
        {
            viewModel.Pilot = await _userManager.FindByIdAsync(viewModel.Pilot.Id);
            viewModel.Helicopter =
                await _context.Helicopters.SingleOrDefaultAsync(h => h.Id == viewModel.Helicopter!.Id);
            viewModel.From = (await _context.Airports.FindAsync(viewModel.From.Id))!;
            viewModel.To = await _context.Airports.FindAsync(viewModel.To!.Id);
            ModelState.Clear();
            if (TryValidateModel(viewModel))
            {
                var flights = viewModel.GetFlights();
                flights.ForEach(f => _context.Add(f));
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Helicopters = await _context.Helicopters.ToListAsync();
            ViewBag.Pilots = await _userManager.GetUsersInRoleAsync("Pilot");
            ViewBag.Airports = await _context.Airports.ToListAsync();
            return View(viewModel);
        }

        // GET: Flights/Edit/5
        [Authorize(Roles = "Administrator, Pilot")]
        public async Task<IActionResult> Edit(Guid? flightId)
        {
            if (User.IsInRole("Pilot")) return RedirectToAction(nameof(EditPilot), new { flightId = flightId });
            if (flightId == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights.FindAsync(flightId);
            if (flight == null)
            {
                return NotFound();
            }

            return View(new FlightViewModel()
            {
                Flight = flight,
                Helicopters = await _context.Helicopters.ToListAsync(),
                Airports = await _context.Airports.ToListAsync(),
                Pilots = await _userManager.GetUsersInRoleAsync("Pilot")
            });
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(FlightViewModel viewModel)
        {
            var flight = await _context.Flights.SingleOrDefaultAsync(f => f.Id == viewModel.Flight.Id);
            string oldJson = JsonSerializer.Serialize(flight);
            if (flight == null) return NotFound(flight);
            flight.From = (await _context.Airports.FindAsync(viewModel.Flight.From.Id))!;
            flight.To = (await _context.Airports.FindAsync(viewModel.Flight.To?.Id))!;
            flight.Helicopter = (await _context.Helicopters.FindAsync(viewModel.Flight.Helicopter?.Id))!;
            flight.Pilot = await _userManager.FindByIdAsync(viewModel.Flight.Pilot.Id);
            flight.ScheduledDeparture = viewModel.Flight.ScheduledDeparture;
            if (flight.From is null || flight.To is null || flight.Pilot is null || flight.Helicopter is null)
                return NotFound("Couldn't find required airport or pilot or helicopter.");
            ModelState.Clear();
            if (TryValidateModel(flight))
            {
                try
                {
                    flight.SetScheduledArrival();
                    _context.Update(flight);
                    flight.Reservations.ForEach(r =>
                    {
                        var message = new UserMessage()

JustInTimeCompany/Controllers/HelicoptersController.cs
using JustInTimeCompany.Models;
using JustInTimeCompany.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JustInTimeCompany.Controllers
{
    public class HelicoptersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public HelicoptersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            var helicopters = await _context.Helicopters.ToListAsync();
            return View(helicopters);
        }

        public async Task<IActionResult> Details(Guid helicopterId, Guid flightId)
        {
            var viewModel = new HelicopterDetailsViewModel()
            {
                HelicopterId = helicopterId,
                FlightId = flightId,
                Helicopter = await _context.Helicopters.SingleOrDefaultAsync(h => h.Id == helicopterId)
            };
            return (viewModel.Helicopter != null)
                ? View(viewModel)
                : NotFound(viewModel.Helicopter);
        }

        public async Task<IActionResult> Clear(Guid helicopterId)
        {
            var helicopter = await _context.Helicopters.FindAsync(helicopterId);
            if (helicopter == null) return NotFound($"Could'nt find the requested helicopter with id {helicopterId}");
            helicopter.Clear();
            _context.Update(helicopter);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

JustInTimeCompany/Controllers/StatisticsController.cs
using JustInTimeCompany.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace JustInTimeCompany.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class StatisticsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private SignInManager<ApplicationUser> _signInManager;

        public StatisticsController(ApplicationDbContext context, SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {
            var flightStatistics = new FlightStatistics(_context.Flights.ToList(), _context.Helicopters.ToList());
            return View(flightStatistics);
        }

        [ValidateAntiForgeryToken]
        [Produces("application/json")]
        public async Task<IActionResult> GetStats()
        {
            var jsonResult = Json(new FlightStatistics(_context.Flights.ToList(), _context.Helicopters.ToList())
                .FillingRates());
            return Ok(jsonResult);
        }
    }
}

JustInTimeCompany/Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager;

@if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrator"))
{
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Helicopters" asp-action="Index">Helicopters</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Statistics" asp-action="Index">Statistics</a>
    </li>
}

JustInTimeCompany/Views/Shared/_FlightListPartial.cshtml
@model IEnumerable<JustInTimeCompany.Models.Flight> 


<p class="fs-5">Feel free to go to the details section or to book a flight.</p>
<div class="text-center">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>From</th>
            <th>To</th>
            <th>Departure</th>
            <th>Arrival</th>
            <th>Pilot</th>
            <th>Seats</th>
            <th>Distance</th>
            <th></th>
            <th></th>
        </tr>

        </thead>
        <tbody>
        @foreach (var flight in Model)
        {
            var seatCount = flight.GetSeatCount();
            var departure = flight.ScheduledDeparture.ToString("dd/MM/yyyy HH\\hmm");
            var arrival = flight.ScheduledArrival.Value.ToString("dd/MM/yyyy HH\\hmm");
            var distance = flight.DistanceKm();
            var fullname = flight.GetPilotFullName();
            <tr class="pe-auto ">
                <td>@flight.From.Name</td>
                <td>@flight.To.Name</td>
                <td>@flight.ScheduledDeparture</td>
                <td>@flight.ScheduledArrival</td>
                <td>@fullname</td>
                <td>@flight.GetSeatCount()</td>
                <td>@distance</td>
                <td>
                    <button class="btn btn-outline-success" onclick="location.href = '@Url.Action("Create", "Reservations", new { flightId = flight.Id })'">Booking</button>
                </td>
                <td>
                    <button class="btn btn-outline-info" onclick="location.href = '@Url.Action("Details", "Flights", new { flightId = flight.Id })'">Details</button>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

JustInTimeCompany/Views/Shared/_FlightMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject RoleManager<IdentityRole> RoleManager

@if (User.IsInRole("Administrator"))
{
    <div class="dropdown my-auto">
        <a class="btn btn-outline-light me-2 dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            Flights
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item" asp-controller="Flights" asp-action="">List</a></li>
            <li><a class="dropdown-item" asp-controller="Flights" asp-action="Create">Create one</a></li>
            <li><a class="dropdown-item" asp-controller="Flights" asp-action="CreateMany">Create many</a></li>
        </ul>
    </div>
}
else
{
    <div class="dropdown my-auto">
        <a class="btn btn-outline-light me-2 dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            Flights
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item" asp-controller="Flights" asp-action="Index">List</a></li>
        </ul>
    </div>
}

JustInTimeCompany/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jitc</title>
    

    <link rel="stylesheet" href="~/myLib/site.min.css" asp-append-version="true" />
    <environment include="Development">
        <LINK REL="shortcut icon" href="~/favicon.ico">
        <link rel="stylesheet" href="/lib/bootstrap/dist/theme/bootstrap.min.css" />    
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/myLib/site.min.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <LINK REL="shortcut icon" href="~/favicon.ico">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/theme/bootstrap.min.css" />    
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/myLib/site.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body class="">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Jitc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <partial name="_AdminMenuPartial"/>
                        <partial name="_FlightMenuPartial"/>
                        <partial name="_ReservationMenuPartial"/>
                    </ul>
                    <partial name="_LoginPartial"/>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Jitc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

JustInTimeCompany/Views/Shared/_ReservationMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager

@if (User.IsInRole("User"))
{
    <div class="dropdown my-auto">
        <a class="btn btn-outline-light me-2 dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            Book
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item" asp-controller="Reservations" asp-action="Index">My books</a></li>
        </ul>
    </div>
}